:gitrepo: https://github.com/cshabazian/Podman-Desktop-Workshop
:includedir: _include
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/

= Introduction to Podman Desktop

[discrete]
== Presented By

* Chip Shabazian

[discrete]
== Introduction
First of all, THANK YOU for registering and participating in *Introduction to Podman Desktop*. This is a cursory introduction to using Podman Desktop to create and deploy containers.  There is so much more functionality that we encourage you to explore after this introductory lab. We hope you enjoy this experience and please don't hesitate to ask questions.

Also, please don't forget to review this session at the completion of this lab.  Your reviews and feedback help us develop and improve labs like these.

NOTE:  This whole effort is done using official Red Hat software and a flatpak installation of Podman Desktop, and although things can likely be set up to work with upstream software components (Fedora, CentOS, etc...), alternate derivatives of RHEL are not tested or validated with these exercises.

[discrete]
== Workshop Abstract

  * link:{includedir}/abstract.adoc[About This Workshop]

[discrete]
== Conventions Used

  * link:{includedir}/conventions.adoc[Documentation Style and Conventions]

[discrete]
== How to Connect

This lab is completed entirely in the desktop GUI

  . Follow instructions provided to connect to the novnc terminal which will display the GUI in a web page

[discrete]
== How to Cut & Paste with novnc

* Text copied in the remote desktop will appear in the clipboard box in noVNC's interface. You can then copy the text from that box to access it in your local clipboard. Any text put into the clipboard box will be sent to the remote clipboard as well.

[discrete]
== Podman Desktop Workshop: EXERCISES

[#toc]
  . link:{includedir}/create-a-container.adoc[*Create a container using an existing Containerfile ]
  . link:{includedir}/copy-a-container.adoc[*Copying an existing Containerfile and modifying it to create a new container ]

[discrete]
== Additional Resources

Podman Desktop

    * link:https://podman-desktop.io/[podman-desktop.io] - This is the official site for Podman Desktop 


[discrete]
== The End

Please remember to fill out the survey.  We really appreciates your time spent with us today and we hope you enjoy the rest of your Red Hat experience.


////
Always end files with a blank line to avoid include problems.
////

